driver/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'driver'

urlpatterns = [
    url(r'^dispatcher_form/',views.DispatcherFormView.as_view(),name='dispatcher_form'),
    url(r'^$', views.index, name='index'),
    #url(r'^driver/create',views.DriverCreate.as_view(),name='create'),
    url(r'^user_form/', views.UserFormView2.as_view(), name='index'),
    url(r'^driver_requests/', views.RequestViewer.as_view(), name='index'),
    url(r'^driver_request_form/', views.DriverRequestFormView.as_view(), name='index'),
    url(r'^customerRequest/',views.CustomerCreate.as_view(),name='customer_create'),
    url(r'^customerlogin/',views.UserFormView.as_view(),name='customer_login')

]

gadgepro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from driver import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('driver.urls')),
]

driver/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.


class Address(models.Model):
    parish = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    number = models.IntegerField()

    class Meta:
        verbose_name_plural = 'Addresses'


class Employee(models.Model):
    e_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class Journey(models.Model):
    UNDERWAY = 'UNDERWAY'
    ENDED = 'ENDED'
    TOBEGIN = 'TOBEGIN'
    JOURNEY_STATES = (
        (UNDERWAY, 'underway'),
        (ENDED, 'ended'),
        (TOBEGIN, 'tobegin'),
    )

    currentLocation = models.CharField(max_length=20)
    destination = models.CharField(max_length=20)
    noOfPeople = models.IntegerField()
    cost = models.DecimalField(max_digits=7, decimal_places=2)
    state = models.CharField(
        max_length=8, choices=JOURNEY_STATES, default='TOBEGIN')


class Vehicle(models.Model):
    carMake = models.CharField(max_length=50)
    carModel = models.CharField(max_length=50)
    carYear = models.CharField(max_length=4)
    carColor = models.CharField(max_length=20)
    licensePlate = models.CharField(max_length=10)


class Driver(Employee):
    AVAILABLE = 'AVAILABLE'
    UNAVAILABLE = 'UNAVAILABLE'

    DRIVER_STATE = (
        (AVAILABLE, 'available'),
        (UNAVAILABLE, 'unavailable')
    )

    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    trn = models.IntegerField()
    cellNum = models.CharField(max_length=10)
    state = models.CharField(
        max_length=12, choices=DRIVER_STATE, default='AVAILABLE')
    currentJourney = models.ForeignKey(
        Journey, models.SET_NULL, blank=True, null=True)


class Customer(User):
    contact = models.CharField(max_length=10)
    location = models.CharField(max_length=10)
    destination = models.CharField(max_length=20)
    noOfPassengers = models.IntegerField()

    class Meta:
        verbose_name = "Customer"

    def get_absolute_url(self):
        return reverse('index')

    def save(self, *args, **kwargs):
    	self.noOfPassengers = 0
    	super(Customer, self).save(*args, **kwargs)


class Dispatcher(Employee, User):
    class Meta:
        verbose_name = 'Dispatcher'

    def dispatch_request(self, request):
        pass


class DriverRequest(models.Model):
    APPROVED = 'APPROVED'
    DECLINED = 'DECLINED'
    REQUEST_STATUS = (
        (APPROVED, 'approved'),
        (DECLINED, 'declined')
    )

    journey = models.ForeignKey(Journey, on_delete=models.CASCADE,related_name='journey')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,related_name='customer')
    state = models.CharField(
        max_length=8, choices=REQUEST_STATUS, default='DECLINED')

driver/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

class DispatcherForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)	

	class Meta:
		model = User
		fields = ['username','email','password']

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)	

	class Meta:
		model = User
		fields = ['username','email','password']


class DriverRequestForm(forms.ModelForm):

	class Meta:
		model = DriverRequest
		fields = []

class JourneyForm(forms.ModelForm):
    
	class Meta:
		model = Journey
		fields = '__all__'

driver/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.urlresolvers import reverse_lazy
from django.views import generic

from django.views.generic.edit import CreateView, FormView


from .models import *
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, DriverRequestForm, JourneyForm


# Create your views here.
def index(request):
    return render(request, 'driver/index.html')


class DispatcherFormView(FormView):
    template_name = 'driver/dispatcher_form.html'
    form_class = UserForm
    success_url = '/thanks/'

    def form_valid(self, form):
        return super().form_valid(form)


class CustomerCreate(CreateView):
    model = Customer
    fields = '__all__'
    template_name = 'driver/customer_form.html'
    success_url = reverse_lazy('driver:index')

    def form_valid(self, form):
        return super().form_valid(form)


class UserFormView(FormView):
    template_name = 'driver/user_form.html'
    form_class = UserForm
    success_url = '/details'


class UserFormView2(FormView):
    template_name = 'driver/user_form.html'
    form_class = UserForm
    success_url = '/thanks/'

    def form_valid(self, form):

        return super().form_valid(form)


class DriverRequestFormView(FormView):
    template_name = 'driver/user_form.html'
    form_class = DriverRequestForm
    success_url = '/thanks/'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        journey_form = JourneyForm()

        return render(request, self.template_name, {'form': form, 'journey_form': journey_form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # create journey

            journey = Journey(currentLocation=request.POST.get('currentLocation', ''), destination=request.POST.get('destination', ''),
                              noOfPeople=int(request.POST.get('noOfPeople', '')), cost=int(request.POST.get('noOfPeople', '')),)

            
            journey.save()

            if Customer.objects.filter(username=request.user.username).exists():
                user = Customer.objects.get(username=request.user.username)
                print(type(request.user))
                driver_request = DriverRequest(
                    journey=journey, customer=user,)

                driver_request.save()
                return HttpResponse('success')
            else:
                return HttpResponse('You must be a customer')

        return render(request, self.template_name, {'form': form})


class RequestViewer(View):
    template_name = 'driver/requests.html'

    def get(self, request, *args, **kwargs):
        requests = DriverRequest.objects.filter(state="DECLINED")

        return render(request, self.template_name, {'requests': requests, })

    def post(self, request, *args, **kwargs):
        print(request.POST)
        drequest = DriverRequest.objects.get(id=request.POST['request_id'])
        drequest.state = request.POST.get("rstate")
        drequest.save()

        return HttpResponse("Successfully changed request to approved")

driver/templates/driver/base.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Asar|Coiny|Roboto|Meera+Inimai|Ramaraja|Shrikhand|Cookie|Cantora+One" rel="stylesheet">

<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'driver:index' %}">GadgePro</a>
    </div>
    <ul class="nav navbar-nav justify-content-center">
      <li class="active nav-item"><a class = "nav-link" href="{% url 'driver:dispatcher_form' %}">Dispatcher Login</a></li>
      <li class="nav-item"><a class = "nav-link" href="{% url 'driver:customer_create' %}">Request a Taxi</a></li>
      <li class="nav-item"><a class = "nav-link" href="#">Leave Feedback</a></li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

driver/templates/driver/customer_form.html
{% extends 'driver/base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% for field in form %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<span class="text-danger small">{{ field.errors }}</span>
								</div>
								<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
								<div class="col-sm-10">
									{{field}}
								</div>
							</div>
						{% endfor %}
						<button class="btn-success" type="submit">Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock%}

driver/templates/driver/dispatcher_form.html
{% extends 'driver/base.html' %}

{% block content %}
	{{form}}
	<button type = "submit">submit</button>
{% endblock %}

driver/templates/driver/driver_form.html
{% extends 'driver/base.html' %}
{% block title %} Request A Driver {%endblock%}

{%block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% for field in form %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<span class="text-danger small">{{ field.errors }}</span>
								</div>
								<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
								<div class="col-sm-10">
									{{field}}
								</div>
							</div>
						{% endfor %}
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

driver/templates/driver/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">
			{{field}}
		</div>
	</div>
{% endfor %}

driver/templates/driver/index.html
{% extends 'driver/base.html' %}

{% block content %}
<div class="container-fluid center-align">
	<h1 class="center-align"> WELCOME TO GADGEPRO </h1>
</div>
{% endblock %}

driver/templates/driver/requests.html
hello

{% for request in requests %}

<form method="post">

    {% csrf_token %}
    customer first name:{{ request.customer.first_name}} <br>
    customer last name:{{ request.customer.last_name}} <br>
    customer current location:{{ request.journey.currentLocation}} <br>
    customer destination:{{ request.journey.destination}} <br>
    customer no passengers:{{ request.journey.noOfPassengers}} <br>
    <input type="hidden" name="request_id" value="{{request.id}}">
    <select name="rstate">
        {% if request.state == "DECLINED" %}
        <option value="DECLINED">Declined</option>
        <option value="APPROVED">Approved</option>
        {% else %}
        <option value="APPROVED">Approved</option>
        <option value="DECLINED">Declined</option>
        {% endif %}
      </select>

    <input type="submit" value="Submit"/>

</form>

{% endfor %}

driver/templates/driver/user_form.html
<form method="post">

    {% csrf_token %}
    {{ form }}
    {{ journey_form }}

    <input type="submit" value="Submit"/>

</form>